print("==================")
print("||              ||")
print("||   Muk Dániel ||")
print("||              ||")
print("||   10/B       ||")
print("||              ||")
print("||  2023.09.07  ||")
print("||              ||")
print("==================")
